global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "gobackend"
    scrape_interval: 10s
    static_configs:
    - targets: ["gobackend:8080"]

  - job_name: "nsqconsumer_links"
    scrape_interval: 10s
    dns_sd_configs:
      - names: ["nsqconsumer_links"]
        type: "A"
        port: 2112
    
  - job_name: "nsqconsumer_rechts"
    scrape_interval: 10s
    dns_sd_configs:
      - names: ["nsqconsumer_rechts"]
        type: "A"
        port: 2112

  - job_name: "grpcconsumer"
    scrape_interval: 10s
    dns_sd_configs:
      - names: ["grpcconsumer"]
        type: "A"
        port: 2112

  - job_name: "natsconsumer"
    scrape_interval: 10s
    dns_sd_configs:
      - names: ["natsconsumer"]
        type: "A"
        port: 2112

  - job_name: "tracingapp"
    scrape_interval: 10s
    dns_sd_configs:
      - names: ["tracingapp"]
        type: "A"
        port: 8001
  
  - job_name: "postgres-exporter"
    scrape_interval: 10s
    static_configs:
    - targets: ["postgres-exporter:9187"]