# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true   # should make it way faster
    
    ## Backend
    - name: Build backend
      working-directory: ./backend
      run: go build -v ./...

    - name: Test
      working-directory: ./backend
      run: go test -v ./...

    ## nsqconsumer
    - name: Build nsqconsumer
      working-directory: ./nsqconsumer
      run: go build -v ./...

    - name: Test
      working-directory: ./nsqconsumer
      run: go test -v ./...

    ## tracingApp
    - name: Build tracingApp
      working-directory: ./tracingApp
      run: go build -v ./...

    - name: Test
      working-directory: ./tracingApp
      run: go test -v ./...
