# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build nessesary containers

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build_test_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true   # should make it way faster
        # This is needed for monorepos. To have the correct path.
        cache-dependency-path: backend/go.sum

    - name: Compile backend Application
      working-directory: ./backend
      run: go build -v -o backend ./... 

    - name: Test backend Application
      working-directory: ./backend
      run: go test -v ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Dockerimage for backend Application
      working-directory: ./backend
      run: docker build --tag backend:v1 .

    # This technically works. The docker image is build and started.
    # Because the backend crashes it, the actions still fail.

    # - name: Try to lauch docker image
    #   run: docker run --rm -p 8080:8080/tcp backend:v1
      


  build_test_nsqconsumer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true   # should make it way faster
        # This is needed for monorepos. To have the correct path.
        cache-dependency-path: nsqconsumer/go.sum

    - name: Build nsqconsumer
      working-directory: ./nsqconsumer
      run: go build -o nsqconsumer -v ./...

    - name: Test nsqconsumer
      working-directory: ./nsqconsumer
      run: go test -v ./...


  build_test_tracingApp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true   # should make it way faster
        # This is needed for monorepos. To have the correct path.
        cache-dependency-path: tracingApp/go.sum

    - name: Build tracingApp
      working-directory: ./tracingApp
      run: go build -v -o tracingapp ./...

    - name: Test tracingApp
      working-directory: ./tracingApp
      run: go test -v ./...